<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVGTeowY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVGTeowY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVGTeowY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVGTeowY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVGTeowY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VGTeowY',
    'container.build_id' => 'b88c286a',
    'container.build_time' => 1585049604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVGTeowY');
