<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'animaux' => [[], ['_controller' => 'App\\Controller\\AnimalController::index'], [], [['text', '/']], [], []],
    'afficher_animal' => [['id'], ['_controller' => 'App\\Controller\\AnimalController::afficherAnimal'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/animal']], [], []],
    'continents' => [[], ['_controller' => 'App\\Controller\\ContinentController::index'], [], [['text', '/continents']], [], []],
    'afficher_continent' => [['id'], ['_controller' => 'App\\Controller\\ContinentController::afficherContinent'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/continent']], [], []],
    'familles' => [[], ['_controller' => 'App\\Controller\\FamilleController::index'], [], [['text', '/familles']], [], []],
    'afficher_famille' => [['id'], ['_controller' => 'App\\Controller\\FamilleController::afficherFamille'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/famille']], [], []],
    'personnes' => [[], ['_controller' => 'App\\Controller\\PersonneController::index'], [], [['text', '/personnes']], [], []],
    'afficher_personne' => [['id'], ['_controller' => 'App\\Controller\\PersonneController::afficherPersonne'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/personne']], [], []],
];
